# Google Cloud Life Sciences Configuration

resources:
  - name: regenomics-pipeline-template
    type: compute.v1.instanceTemplate
    properties:
      properties:
        machineType: n1-standard-4
        disks:
          - deviceName: boot
            type: PERSISTENT
            boot: true
            autoDelete: true
            initializeParams:
              sourceImage: projects/cloud-life-sciences/global/images/family/cos-stable
        networkInterfaces:
          - network: global/networks/default
            accessConfigs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        serviceAccounts:
          - email: default
            scopes:
              - https://www.googleapis.com/auth/cloud-platform

  - name: regenomics-pipeline-group
    type: compute.v1.instanceGroupManager
    properties:
      zone: us-central1-a
      targetSize: 1
      instanceTemplate: $(ref.regenomics-pipeline-template.selfLink)
      namedPorts:
        - name: http
          port: 80